// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package avmsgraphsdkgo

import (
    i25911dc319edd61cbac496af7eab5ef20b6069a42515e22ec6a9bc97bf598488 "github.com/microsoft/kiota-serialization-json-go"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i4bcdc892e61ac17e2afc10b5e2b536b29f4fd6c1ad30f4a5a68df47495db3347 "github.com/microsoft/kiota-serialization-form-go"
    i56887720f41ac882814261620b1c8459c4a992a0207af547c4453dd39fabc426 "github.com/microsoft/kiota-serialization-multipart-go"
    i7294a22093d408fdca300f11b81a887d89c47b764af06c8b803e2323973fdb83 "github.com/microsoft/kiota-serialization-text-go"
    i37eb5ab0f38ac984a1c142676e92301b71b857da8f13c9fb50fd2cd4a04db058 "github.com/aurva-io/avmsgraph-sdk-go/directoryroles"
    i68804911f5e9998ba51223a3eeb2f3b303a654e0f07d1a255cef4dc5970f6e4b "github.com/aurva-io/avmsgraph-sdk-go/directoryobjects"
    i83001fb13b96140625b0a2c603da39d73efd6925542de671b0b2817e52d67648 "github.com/aurva-io/avmsgraph-sdk-go/rolemanagement"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i9020c3bbd8d38850ea417c6a90ea24a8cef415af5e32f3fa556a720340d8d416 "github.com/aurva-io/avmsgraph-sdk-go/users"
    ic360260a68923c9f4fcbfd3992b2d41e83757a17bbee01ed16815224f4a74055 "github.com/aurva-io/avmsgraph-sdk-go/applications"
    icaed50e241b4ef2f3c43f7bebb599ecd3b5603f36d1533f1745a9dc7bbbb1a54 "github.com/aurva-io/avmsgraph-sdk-go/directoryroletemplates"
    ie8677ce2c7e1b4c22e9c3827ecd078d41185424dd9eeb92b7d971ed2d49a392e "github.com/microsoft/kiota-abstractions-go/store"
    ieead57c1177be5c067fa2b2c6e081444c053b04bce9c644b80a75f7e699ce9e3 "github.com/aurva-io/avmsgraph-sdk-go/groups"
)

// ApiClient the main entry point of the SDK, exposes the configuration and the fluent API.
type ApiClient struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Applications provides operations to manage the collection of application entities.
// returns a *ApplicationsRequestBuilder when successful
func (m *ApiClient) Applications()(*ic360260a68923c9f4fcbfd3992b2d41e83757a17bbee01ed16815224f4a74055.ApplicationsRequestBuilder) {
    return ic360260a68923c9f4fcbfd3992b2d41e83757a17bbee01ed16815224f4a74055.NewApplicationsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewApiClient instantiates a new ApiClient and sets the default values.
func NewApiClient(requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter, backingStore ie8677ce2c7e1b4c22e9c3827ecd078d41185424dd9eeb92b7d971ed2d49a392e.BackingStoreFactory)(*ApiClient) {
    m := &ApiClient{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}", map[string]string{}),
    }
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultSerializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriterFactory { return i25911dc319edd61cbac496af7eab5ef20b6069a42515e22ec6a9bc97bf598488.NewJsonSerializationWriterFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultSerializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriterFactory { return i7294a22093d408fdca300f11b81a887d89c47b764af06c8b803e2323973fdb83.NewTextSerializationWriterFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultSerializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriterFactory { return i4bcdc892e61ac17e2afc10b5e2b536b29f4fd6c1ad30f4a5a68df47495db3347.NewFormSerializationWriterFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultSerializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriterFactory { return i56887720f41ac882814261620b1c8459c4a992a0207af547c4453dd39fabc426.NewMultipartSerializationWriterFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultDeserializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNodeFactory { return i25911dc319edd61cbac496af7eab5ef20b6069a42515e22ec6a9bc97bf598488.NewJsonParseNodeFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultDeserializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNodeFactory { return i7294a22093d408fdca300f11b81a887d89c47b764af06c8b803e2323973fdb83.NewTextParseNodeFactory() })
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RegisterDefaultDeserializer(func() i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNodeFactory { return i4bcdc892e61ac17e2afc10b5e2b536b29f4fd6c1ad30f4a5a68df47495db3347.NewFormParseNodeFactory() })
    if m.BaseRequestBuilder.RequestAdapter.GetBaseUrl() == "" {
        m.BaseRequestBuilder.RequestAdapter.SetBaseUrl("https://graph.microsoft.com/v1.0")
    }
    m.BaseRequestBuilder.PathParameters["baseurl"] = m.BaseRequestBuilder.RequestAdapter.GetBaseUrl()
    m.BaseRequestBuilder.RequestAdapter.EnableBackingStore(backingStore);
    return m
}
// DirectoryObjects the directoryObjects property
// returns a *DirectoryObjectsRequestBuilder when successful
func (m *ApiClient) DirectoryObjects()(*i68804911f5e9998ba51223a3eeb2f3b303a654e0f07d1a255cef4dc5970f6e4b.DirectoryObjectsRequestBuilder) {
    return i68804911f5e9998ba51223a3eeb2f3b303a654e0f07d1a255cef4dc5970f6e4b.NewDirectoryObjectsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// DirectoryRoles provides operations to manage the collection of directoryRole entities.
// returns a *DirectoryRolesRequestBuilder when successful
func (m *ApiClient) DirectoryRoles()(*i37eb5ab0f38ac984a1c142676e92301b71b857da8f13c9fb50fd2cd4a04db058.DirectoryRolesRequestBuilder) {
    return i37eb5ab0f38ac984a1c142676e92301b71b857da8f13c9fb50fd2cd4a04db058.NewDirectoryRolesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// DirectoryRoleTemplates provides operations to manage the collection of directoryRoleTemplate entities.
// returns a *DirectoryRoleTemplatesRequestBuilder when successful
func (m *ApiClient) DirectoryRoleTemplates()(*icaed50e241b4ef2f3c43f7bebb599ecd3b5603f36d1533f1745a9dc7bbbb1a54.DirectoryRoleTemplatesRequestBuilder) {
    return icaed50e241b4ef2f3c43f7bebb599ecd3b5603f36d1533f1745a9dc7bbbb1a54.NewDirectoryRoleTemplatesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Groups provides operations to manage the collection of group entities.
// returns a *GroupsRequestBuilder when successful
func (m *ApiClient) Groups()(*ieead57c1177be5c067fa2b2c6e081444c053b04bce9c644b80a75f7e699ce9e3.GroupsRequestBuilder) {
    return ieead57c1177be5c067fa2b2c6e081444c053b04bce9c644b80a75f7e699ce9e3.NewGroupsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// RoleManagement the roleManagement property
// returns a *RoleManagementRequestBuilder when successful
func (m *ApiClient) RoleManagement()(*i83001fb13b96140625b0a2c603da39d73efd6925542de671b0b2817e52d67648.RoleManagementRequestBuilder) {
    return i83001fb13b96140625b0a2c603da39d73efd6925542de671b0b2817e52d67648.NewRoleManagementRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Users provides operations to manage the collection of user entities.
// returns a *UsersRequestBuilder when successful
func (m *ApiClient) Users()(*i9020c3bbd8d38850ea417c6a90ea24a8cef415af5e32f3fa556a720340d8d416.UsersRequestBuilder) {
    return i9020c3bbd8d38850ea417c6a90ea24a8cef415af5e32f3fa556a720340d8d416.NewUsersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
